export const SERVER_HAS_ERRORED = 'SERVER_HAS_ERRORED';
export const SERVER_IS_LOADING = 'SERVER_IS_LOADING';
export const SERVER_RESPONSE_SUCCESS = 'SERVER_RESPONSE_SUCCESS';
export const GET_INITAL_STATE = 'GET_INITAL_STATE';
export const DELETE_MASSAGE = 'DELETE_MASSAGE';
export const ADD_MASSAGE = 'ADD_MASSAGE';



