export const SERVER_HAS_ERRORED = 'SERVER_HAS_ERRORED';
export const SERVER_IS_LOADING = 'SERVER_IS_LOADING';
export const SERVER_RESPONSE_SUCCESS = 'SERVER_RESPONSE_SUCCESS';
export const AUTH_USER = 'AUTH_USER';
